version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: cryptowallet-postgres
    environment:
      POSTGRES_DB: cryptowallet
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: crypto-wallet-manager
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cryptowallet
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
    depends_on:
      - postgres
volumes:
  postgres_data:
