spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cryptowallet
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080

logging:
  level:
    root: INFO
